---
title: "Secret primaire avancé"
format: html
editor: visual
---

# Secret primaire avancé

La gestion du secret primaire appelle parfois :

-   des règles de secret spécifiques, non envisagées dans les wrappers actuels de `GaussSuppression`

-   un besoin de connaître la nature du secret primaire (distinguer fréquence et dominance) pour la documentation des fichiers de diffusion (`allDominance=TRUE`)

-   des exceptions (autorisation spéciale des unités concernées) (`wg`)

Il arrive que certaines sources aient des règles de secret primaire plus complexes, qu'une règle de fréquence ou de dominance. En effet, la BTS par exemple combine plusieurs règles de fréquences et de dominance sur différents indicateurs. De plus, on peut vouloir mettre en place des exceptions de secret primaire. Pour cela, il faut utiliser l'argument `primary` lors de l'appel à une fonction de secret de `GaussSuppression`.

::: callout-warning
## Attention

Quand on utilise l'argument `primary` les autres arguments de secret primaires tels que `n`, `k` ou `maxN` sont ignorés.
:::
